# Generated by Django 5.0.dev20230305130119 on 2023-06-05 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=20)),
                ('opis', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=20)),
                ('prezime', models.CharField(max_length=20)),
                ('adresa', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=20, primary_key='true', serialize=False)),
                ('ime', models.CharField(max_length=35)),
                ('opis', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='files/')),
                ('cena', models.IntegerField()),
                ('kolicina', models.IntegerField()),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.kategorija')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prodazba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_prodazba', models.DateField(auto_now=True)),
                ('klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.klient')),
                ('produkti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
    ]
