# Generated by Django 5.0.dev20230305130119 on 2023-06-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
